server:
  port: 9000

spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    order-service: /order/**
    product-service: /product/**
  ignored-patterns: /*-service/**
  #ignored-services: product-service
  
env: pilot
branch: pilot  
