server:
  port: 8781

spring:
  application:
    name: order-service
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 2000
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 4000
        readTimeout: 4000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
env:
  test: default
branch:
  test: main
